### ISSUE TITLE
Kontrolle der Pumpen bei PV Überschuss

### ISSUE THREAD

**Issue by OktaMen** [rrov1/SwimSpa#1]
Ein Adapter oder eine funktionierende Api oder Datenpunkte wären Hammer.

Da die Strompreise bei uns ums doppelte gestiegen sind, möchte ich den Stromverbrauch des Whirlpools optimieren.

Wenn PV-Überschuss vorhanden ist, dann soll der Whirlpool heizen und filtern. Sobald der Überschuss zu wenig wird, sollte er wieder stoppen. Ich würde noch in weitere Datenpunkte die tägliche Pumpdauer sowie max. und min. Werte für die Temp. angeben.

Ich bräuchte eigentlich nur eine gute Kontrolle für den Whirlpool, 
alles andere würde ich mit JavaScript oder Blockly gut hinbekommen.

**Comment by rrov1** [comment]
> Ein Adapter oder eine funktionierende Api oder Datenpunkte wären Hammer.

Also der aktuelle Stand ist kein Adapter aber nahe dran ;-) . Hast du schon entsprechend der Anleitung die Installation durchgeführt? Wenn ja, hast du einen Satz von Datenpunkten die den Status deines SpaController darstellen, die regelmäßig (minütlich) aktualisiert werden, sowie Datenpunkte die du setzen kannst um Aktionen am SpaController ausführen zu können. Beispiel von mir:
![image](https://user-images.githubusercontent.com/45232990/232580654-11a2b564-5641-4ba5-b376-4ac5d33e19ca.png)


> Wenn PV-Überschuss vorhanden ist, dann soll der Whirlpool heizen und filtern. Sobald der Überschuss zu wenig wird, sollte er wieder stoppen. Ich würde noch in weitere Datenpunkte die tägliche Pumpdauer sowie max. und min. Werte für die Temp. angeben.

Heizen: Nach meinem Verständnis der in.touch SpaController und der geckolib kann man das nicht einfach mal so aktivieren. Aus diesem Grund setze ich eine Zieltemperatur bei der geheizt werden muss (z.B. über den Datenpunkt: javascript.0.Datenpunkte.SwimSpa.0.ZielTemperatur, bei mir grundsätzlich manuell) und dann schalte ich einen Wasserpflegemodus ein (z.B. Standard über den Datenpunkt: javascript.0.Datenpunkte.SwimSpa.0.WasserpflegeSwitch). Letzteres lasse ich bei PV-Überschuss natürlich von einem Skript machen.

Filtern: Hierfür habe ich aktuell noch keine Lösung um die Filterzeiten über Datenpunkte zu steuern. Bisher hatte ich persönlich da keinen Bedarf, meine beiden Filterpumpen verbrauchen so um die 360W und laufen über die normale Zeitsteuerung. Ich schau aber mal was so über die geckolib zu steuern geht, von der bin ich halt abhängig.

Schreib mir mal ob dir das so hilft.

**Comment by OktaMen** [comment]
@rrov1 Danke für dein Feedback. Ich werde es nächste Woche mal testen.
Warte gerade noch auf meinen in.touch.

**Comment by OktaMen** [comment]
Hi @rrov1 
leider habe ich eine Fehlermeldung in den logs im ioBroker. Hast du eine Ahnung was das bedeutet?

`script.js.Spa.SpaUpdateConfig: *** stderr: Error: Command failed: python3 /SpaController/spa_config.py 59646673-a656-xxxx-xxxx-45c4bgwi681 http://172.16.xx.xxx:8087 javascript.0.Datenpunkte.SwimSpa Traceback (most recent call last): File "/SpaController/spa_config.py", line 174, in <module> asyncio.run(main()) File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run return loop.run_until_complete(main) File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete return future.result() File "/SpaController/spa_config.py", line 34, in main async with SampleSpaMan(CLIENT_ID, spa_address=None) as spaman: File "/usr/local/lib/python3.7/dist-packages/geckolib/async_spa_manager.py", line 231, in __aenter__ await AsyncTasks.__aenter__(self) File "/usr/local/lib/python3.7/dist-packages/geckolib/async_tasks.py", line 15, in __aenter__ self.add_task(self._tidy(), "Tidy tasks", "ASYNC") File "/usr/local/lib/python3.7/dist-packages/geckolib/async_tasks.py", line 22, in add_task task = asyncio.create_task(coroutine, name=f"{key_}:{name_}") TypeError: create_task() got an unexpected keyword argument 'name' sys:1: RuntimeWarning: coroutine 'AsyncTasks._tidy' was never awaited`

**Comment by rrov1** [comment]
Hallo,
ich habe mal ein bisschen recherchiert. Lt. Tante google liegt es an der Python Version. Wenn man nach "TypeError: create_task() got an unexpected keyword argument 'name' sys:1:" sucht bekommt man als eins der ersten Ergebnisse:
- https://github.com/Defxult/reactionmenu/issues/4

und wenn man dann in https://docs.python.org/3/whatsnew/3.8.html nachschaut findet man;
> ... Asyncio tasks can now be named, either by passing the name keyword argument to asyncio.create_task() ...

Da das bei dir installierte Python 3.7 eh nur noch bis zum 27 Jun 2023 Security Fixes bekommt (vgl. hier: https://endoflife.date/python) wäre mein Vorschlag mindestens auf Python 3.8 zu aktualisieren. Ich persönlich nutze 3.9 und ich weiß, das es mit 3.10 auch läuft. Ich werde auch mal die Anleitung ergänzen.

rrov1

**Comment by OktaMen** [comment]
Hi,
also im Terminal konnte ich mit der Gecko Shell alle Befehle ausführen und bekam auch die richtige Rückmeldung.
Aber o.k. ich versuche eine neuere Version.

Also ich habe/hatte einige Probleme bei der Python installation, den einfach nur mit "pip" ging es nicht und mit "sudo apt-get install python3" wird immer die 3.7 Version installiert.
Es scheint, dass der Standard-Paketmanager für die Linux-Distribution Python 3.7 als neueste Version anbietet.

Erst habe ich mit dieser Anleitung mal eine neuere Version installiert und dann auf die neueste Version verwiesen.
https://raspberrytips.com/install-latest-python-raspberry-pi/

Dann noch "pip" installieren mit
`sudo pip3 install geckolib`

UND... wieder funktioniert es nicht, da immer die Version 3.7 verwendet wird, wenn ich geckolib mit `sudo pip3 install geckolib` installieren möchte.
Wenn ich `sudo python3.10 -m pip install geckolib` für die neueste Version verwende, dann bekomme ich einen SSL-Fehler im Terminal.

Also die geckolib mit `sudo python3.7 -m pip uninstall geckolib` wieder deinstalliert.
Dann habe ich eine neue Python Version mit OpenSSL mit folgenden Befehlen installiert.
3.10.11 hatte ich ja bereits downgeloaded und entpackt.
`cd Python-3.10.11`
`./configure --with-openssl=/usr/local/ssl --enable-optimizations`
`make -j $(nproc)`
`sudo make altinstall`

ABER: Immer noch das SSL Problem.
Hier mal die Fehlermeldung:

> pi@raspberrypi4-iob:~ $ python --version
Python 3.10.11
pi@raspberrypi4-iob:~ $ sudo python3.10 -m pip install geckolib
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/geckolib/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/geckolib/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/geckolib/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/geckolib/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/geckolib/
Could not fetch URL https://pypi.org/simple/geckolib/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/geckolib/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/geckolib/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/geckolib/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/geckolib/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/geckolib/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/geckolib/
Could not fetch URL https://www.piwheels.org/simple/geckolib/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='www.piwheels.org', port=443): Max retries exceeded with url: /simple/geckolib/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
ERROR: Could not find a version that satisfies the requirement geckolib (from versions: none)
ERROR: No matching distribution found for geckolib
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
Could not fetch URL https://www.piwheels.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='www.piwheels.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping

Keine Ahnung. Ich bin am Ende meines Lateins.
Wie gesagt, mit den folgenden Befehlen kann ich im Terminal die Geckolib ausführen.

`python3.7`
> `from geckolib import GeckoShell`
> `GeckoShell.run()`

**Comment by OktaMen** [comment]
Vielleicht noch ein update.
Ich habe es geschafft mit der python Version 3.9.15.

Aber jetzt habe ich einen anderen error in den logs im ioBroker:

> script.js.Spa.SpaUpdateValues: *** stderr: Error: Command failed: python3 /SpaController/spa_updateBulk.py 1axxxx2a-c425-d460-53494-0fdfj670bdf1 http://172.16.xx.xxx:8087 , javascript.0.Datenpunkte.SwimSpa Traceback (most recent call last): File "/SpaController/spa_updateBulk.py", line 3, in <module> import requests ModuleNotFoundError: No module named 'requests'
--

Weisst du, was das bedeutet?

**Comment by rrov1** [comment]
> Weisst du, was das bedeutet?

Hallo,
ja, diese Version von Python (3.9.15) kann die zusätzlich benötigte Bibliothek "requests" nicht finden. In der Anleitung war ja ein Schritt:
sudo pip3 install requests
dabei. 

Pobiere mal:
sudo python3.9.15 -m pip install requests

Auf den Raspi's ist's irgendwie hakelig mit Python, Ich hatte schon einen anderen Fall wo wir uns mühsam der Lösung genähert hatten. Ich benutze keinen Raspi, sondern einen Proxmox x86-Container.

rrov1

**Comment by OktaMen** [comment]
Ja das hatte ich schon gemacht.
Das script versucht aber immer auf die vom Raspberry pi vorinstallierte Version 3.7 zuzugreifen und nicht auf meine 3.9.
Obwohl ich folgendes mit alias angelegt habe.

> pi@raspberrypi4-iob:~ $ python3 --version
> Python 3.9.15
> pi@raspberrypi4-iob:~ $ python --version
> Python 3.9.15
> pi@raspberrypi4-iob:~ $

**Comment by OktaMen** [comment]
Ich habe es. Warum ich da nicht gleich drauf gekommen bin.
Ich konnte ja die Befehle in der Console ausführen mit `python3.9`
also habe ich in deiner global.js den `const SPA_EXECUTEABLE = "python3.9"` geändert.

Und siehe da ... jetrzt kommt etwas im ioBroker an :-)

**Comment by OktaMen** [comment]
Aber trotzdem viele Fehler in den logs:

> [Dachterrasse(SPA68:xx:xx:xx:xx:xx)] 2023-04-26 20:54:22,893> INFO Found 1 spas ... [Dachterrasse(SPA68:xx:xx:be:xx:xx)] Traceback (most recent call last): File "/SpaController/spa_updateBulk.py", line 170, in <module> asyncio.run(main()) File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run return loop.run_until_complete(main) File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete return future.result() File "/SpaController/spa_updateBulk.py", line 81, in main await spaman.async_connect(spa_identifier=spa) File "/usr/local/lib/python3.9/site-packages/geckolib/async_spa_manager.py", line 334, in async_connect return await self.async_connect_to_spa(spa_descriptors[0]) File "/usr/local/lib/python3.9/site-packages/geckolib/async_spa_manager.py", line 296, in async_connect_to_spa await self._handle_event(GeckoSpaEvent.CONNECTION_STARTED) File "/usr/local/lib/python3.9/site-packages/geckolib/async_spa_manager.py", line 456, in _handle_event self._reconnect_button = GeckoAsyncSpaMan.ReconnectButton(self) File "/usr/local/lib/python3.9/site-packages/geckolib/async_spa_manager.py", line 36, in __init__ spaman.unique_id, "Reconnect", spaman.spa_name, "RECONNECT" File "/usr/local/lib/python3.9/site-packages/geckolib/async_spa_manager.py", line 373, in unique_id assert self._spa_identifier is not None AssertionError

oder

> ERROR Exception during spa connection Traceback (most recent call last): File "/usr/local/lib/python3.9/site-packages/geckolib/async_spa.py", line 367, in connect await self._connect() File "/usr/local/lib/python3.9/site-packages/geckolib/async_spa.py", line 334, in _connect if not await self.struct.get( File "/usr/local/lib/python3.9/site-packages/geckolib/driver/async_spastruct.py", line 76, in get if await request.wait_for_response(protocol): File "/usr/local/lib/python3.9/site-packages/geckolib/driver/udp_protocol_handler.py", line 143, in wait_for_response await asyncio.sleep(GeckoConstants.ASYNCIO_SLEEP_TIMEOUT_FOR_YIELD) File "/usr/local/lib/python3.9/asyncio/tasks.py", line 652, in sleep return await future asyncio.exceptions.CancelledError Traceback (most recent call last): File "/SpaController/spa_updateBulk.py", line 170, in <module> asyncio.run(main()) File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run return loop.run_until_complete(main) File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete return future.result() File "/SpaController/spa_updateBulk.py", line 91, in main print(f'Heizung vorhanden {facade.water_heater.is_present}') AttributeError: 'NoneType' object has no attribute 'water_heater

**Comment by rrov1** [comment]
> Aber trotzdem viele Fehler in den logs:

Also den zweiten Fehler kennen ich, der tritt auch bei mir auf. Das kommt vom Skript SpaUpdateValues.js/spa_updateBulk.py, welches jede Minute gestartet wird (Zeile 4 in SpaUpdateeValues.js) um Änderungen von Werten wie z.B. der Wassertemperatur, Pumpenstatus usw. vom SpaController auszulesen. Von den 1.440 Aufrufen pro Tag sind bei mir gestern lt. Protokoll: 51 fehlgeschlagen. Eine Quote so in der Höhe, vielleicht bis zu 200, ist leider normal. Hängt u.a. damit zusammen wie die geckolib mit dem SpaController kommuniziert, dann natürlich das minütliche pollen, vielleicht noch die App die parallel was tut, leider jenseits von perfekt :-(.

Den ersten Fehler finde ich bisher bei mir nicht im Protokoll. Kannst du bitte mal zählen wie oft der Auftritt innerhalb von 24 Stunden. Im worst case muss ich den Programmierer der [geckolib](https://github.com/gazoodle/geckolib) fragen.

rrov1

**Comment by OktaMen** [comment]
Also ich habe den Fehler jede Minute. Habe die erste Zeile des logs aber irgendwie nicht kopiert. Es sieht eigentlich wie folgt aus.

> script.js.Spa.SpaUpdateValues: *** stderr: Error: Command failed: python3.9 /SpaController/spa_updateBulk.py xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx http://172.16.xx.xxx:8087 SPA68:xx:xx:xx:xx:xx, javascript.0.Datenpunkte.SwimSpa2023-04-28 08:40:04,989> INFO Found 1 spas ...[Dachterrasse(SPA68:xx:xx:xx:xx:xx)] 2023-04-26 20:54:22,893> INFO Found 1 spas ... [Dachterrasse(SPA68:xx:xx:be:xx:xx)] Traceback (most recent call last): File "/SpaController/spa_updateBulk.py", line 170, in asyncio.run(main()) File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run return loop.run_until_complete(main) File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete return future.result() File "/SpaController/spa_updateBulk.py", line 81, in main await spaman.async_connect(spa_identifier=spa) File "/usr/local/lib/python3.9/site-packages/geckolib/async_spa_manager.py", line 334, in async_connect return await self.async_connect_to_spa(spa_descriptors[0]) File "/usr/local/lib/python3.9/site-packages/geckolib/async_spa_manager.py", line 296, in async_connect_to_spa await self._handle_event(GeckoSpaEvent.CONNECTION_STARTED) File "/usr/local/lib/python3.9/site-packages/geckolib/async_spa_manager.py", line 456, in _handle_event self._reconnect_button = GeckoAsyncSpaMan.ReconnectButton(self) File "/usr/local/lib/python3.9/site-packages/geckolib/async_spa_manager.py", line 36, in init spaman.unique_id, "Reconnect", spaman.spa_name, "RECONNECT" File "/usr/local/lib/python3.9/site-packages/geckolib/async_spa_manager.py", line 373, in unique_id assert self._spa_identifier is not None AssertionError

--

**Comment by rrov1** [comment]
Ok, jede Minute ist schlecht. Bitte deaktiviere auf jeden Fall erst mal im Javascript-Adapter das Skript SpaUpdateValues.js, denn solange wir die Ursache nicht gefunden haben, macht das keinen Sinn, dass das Skript läuft, es müllt ja nur das ioBroker Protokoll voll.
Dann habe ich er mal noch folgende Fragen:
- ioBroker und der in.touch-Controller liegen im gleichen Netz, keine Firewall oder sonst irgendwas dazwischen?
- in.touch-App funktioniert einwandfrei?
- Entsprechend der Anleitung hast du ja zuerst die Skripte SpaUpdateConfig.js/spa_config.py installiert und aktiviert. Lief das Skript erfolgreich, sprich sind in den Datenpunkten: 
- javascript.0.Datenpunkte.SwimSpa.1.Name, 
- javascript.0.Datenpunkte.SwimSpa.1.Sensoren.RF_Signal.State oder
- javascript.0.Datenpunkte.SwimSpa.1.WasserpflegeModi
Werte enthalten?
- Wenn Werte enthalten sind, wann (Uhrzeit) wurden die zuletzt gesetzt? Das Skript läuft tgl. aller 6 Stunden, also 0:00, 6:00, 12:00 oder 18:00 Uhr.
- Wenn die Werte zu alt sind, lege doch bitte mal einen Auszug des Protokolls für dieses Skript hier bei.

Im nächsten Schritt werden wir dann eins der beiden Skripte mal manuell ausführen und noch etwas mehr Logging der geckolib aktivieren in der Hoffnung, was zu sehen. Aber erst mal diesen Schritt hier.

rrov1

**Comment by OktaMen** [comment]
Ich habe nun nochmal alle Datenpunkte gelöscht und habe in der "SpaVariablen.js" die createDatapoints(1, 3, true); geändert. Vorher wurden 2 Datenpunkte erstellt und das hat wohl den Fehler ausgelöst.
Jetzt seit 15 Minuten hatte ich keinen Error mehr in den Logs. Alle Datenpunkte sehen aktuell aus und ich kann auch die Pumpen schalten.

@rrov1 besteht die Möglichkeit, dass ich auch die Zeitpläne der einzelnen Wasserpflege Modi anpasse?
Das würde mir helfen, den Stromverbrauch auf die PV-Anlage abzustimmen. Weil mit der Änderung des Starts und des Stops, könnte ich die Pumpzeit/Filterzeit beeinflussen.

Oder hättest du eine andere Idee?

**Comment by rrov1** [comment]
Schön zu hören das es jetzt läuft, ich änder mal noch den Defaultwert im Aufruf von createDatapoints(), weil es wohl eher selten sein wird, das jemand 2 SpaController hat so wie ich.

Die Zeitpläne der Wasserpflege Modi kann man mit der [geckolib](https://github.com/gazoodle/geckolib) nicht beeinflussen, hatte die Frage schon mal. habe eben das API noch mal quergecheckt. 

Wenn du sowas realisieren willst könntest du ungenutzte Modi "missbrauchen". Ich persönlich brauche nur Abwesend  (da wird auch immer gefiltert, das geht nicht anders) und Standard (filtern und kein Sparmodus), sprich die anderen drei sind frei. Man könnte jetzt:
- Abwesend == alles aus: kein Filter + 24/7 Sparmodus
- die anderen vier Modi = jeden Tag um 10, 12, 14 und 16 Uhr je 2h Filtern und zur gleichen Zeit auch kein Sparmodus (sprich heizen möglich)
Dazu ein ioBroker Skript, das tagsüber den PV-Überschuss kalkuliert und je nach Uhrzeit bei Überschuss einen der vier Modi aktiviert oder eben Abwesend einstellt.

**Comment by OktaMen** [comment]
Ja das ist eigentlich keine so schlechte Idee und eine Möglichkeit dies zu umgehen.
Ich schaue mir das bei Gelegenheit an. Aber ich denke, es müsste sich so ganz gut umsetzen lassen.

Danke dir nochmals und, ich werde berichten. 😊

**Comment by rrov1** [comment]
Müsste sich mittlerweile erledigt haben :-)
